using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Humanizer.In;
using Terraria.ID;
using Terraria;
using Microsoft.Xna.Framework;

namespace DragonballPichu.Common.Systems
{
    internal class Colors
    {
        public static Color Transparent = Color.Transparent;
        public static Color AliceBlue = Color.AliceBlue;
        public static Color AntiqueWhite = Color.AntiqueWhite;
        public static Color Aqua = Color.Aqua;
        public static Color Aquamarine = Color.Aquamarine;
        public static Color Azure = Color.Azure;
        public static Color Beige = Color.Beige;
        public static Color Bisque = Color.Bisque;
        public static Color Black = Color.Black;
        public static Color BlanchedAlmond = Color.BlanchedAlmond;
        public static Color Blue = Color.Blue;
        public static Color BlueViolet = Color.BlueViolet;
        public static Color Brown = Color.Brown;
        public static Color BurlyWood = Color.BurlyWood;
        public static Color CadetBlue = Color.CadetBlue;
        public static Color Chartreuse = Color.Chartreuse;
        public static Color Chocolate = Color.Chocolate;
        public static Color Coral = Color.Coral;
        public static Color CornflowerBlue = Color.CornflowerBlue;
        public static Color Cornsilk = Color.Cornsilk;
        public static Color Crimson = Color.Crimson;
        public static Color Cyan = Color.Cyan;
        public static Color DarkBlue = Color.DarkBlue;
        public static Color DarkCyan = Color.DarkCyan;
        public static Color DarkGoldenrod = Color.DarkGoldenrod;
        public static Color DarkGray = Color.DarkGray;
        public static Color DarkGreen = Color.DarkGreen;
        public static Color DarkKhaki = Color.DarkKhaki;
        public static Color DarkMagenta = Color.DarkMagenta;
        public static Color DarkOliveGreen = Color.DarkOliveGreen;
        public static Color DarkOrange = Color.DarkOrange;
        public static Color DarkOrchid = Color.DarkOrchid;
        public static Color DarkRed = Color.DarkRed;
        public static Color DarkSalmon = Color.DarkSalmon;
        public static Color DarkSeaGreen = Color.DarkSeaGreen;
        public static Color DarkSlateBlue = Color.DarkSlateBlue;
        public static Color DarkSlateGray = Color.DarkSlateGray;
        public static Color DarkTurquoise = Color.DarkTurquoise;
        public static Color DarkViolet = Color.DarkViolet;
        public static Color DeepPink = Color.DeepPink;
        public static Color DeepSkyBlue = Color.DeepSkyBlue;
        public static Color DimGray = Color.DimGray;
        public static Color DodgerBlue = Color.DodgerBlue;
        public static Color Firebrick = Color.Firebrick;
        public static Color FloralWhite = Color.FloralWhite;
        public static Color ForestGreen = Color.ForestGreen;
        public static Color Fuchsia = Color.Fuchsia;
        public static Color Gainsboro = Color.Gainsboro;
        public static Color GhostWhite = Color.GhostWhite;
        public static Color Gold = Color.Gold;
        public static Color Goldenrod = Color.Goldenrod;
        public static Color Gray = Color.Gray;
        public static Color Green = Color.Green;
        public static Color GreenYellow = Color.GreenYellow;
        public static Color Honeydew = Color.Honeydew;
        public static Color HotPink = Color.HotPink;
        public static Color IndianRed = Color.IndianRed;
        public static Color Indigo = Color.Indigo;
        public static Color Ivory = Color.Ivory;
        public static Color Khaki = Color.Khaki;
        public static Color Lavender = Color.Lavender;
        public static Color LavenderBlush = Color.LavenderBlush;
        public static Color LawnGreen = Color.LawnGreen;
        public static Color LemonChiffon = Color.LemonChiffon;
        public static Color LightBlue = Color.LightBlue;
        public static Color LightCoral = Color.LightCoral;
        public static Color LightCyan = Color.LightCyan;
        public static Color LightGoldenrodYellow = Color.LightGoldenrodYellow;
        public static Color LightGray = Color.LightGray;
        public static Color LightGreen = Color.LightGreen;
        public static Color LightPink = Color.LightPink;
        public static Color LightSalmon = Color.LightSalmon;
        public static Color LightSeaGreen = Color.LightSeaGreen;
        public static Color LightSkyBlue = Color.LightSkyBlue;
        public static Color LightSlateGray = Color.LightSlateGray;
        public static Color LightSteelBlue = Color.LightSteelBlue;
        public static Color LightYellow = Color.LightYellow;
        public static Color Lime = Color.Lime;
        public static Color LimeGreen = Color.LimeGreen;
        public static Color Linen = Color.Linen;
        public static Color Magenta = Color.Magenta;
        public static Color Maroon = Color.Maroon;
        public static Color MediumAquamarine = Color.MediumAquamarine;
        public static Color MediumBlue = Color.MediumBlue;
        public static Color MediumOrchid = Color.MediumOrchid;
        public static Color MediumPurple = Color.MediumPurple;
        public static Color MediumSeaGreen = Color.MediumSeaGreen;
        public static Color MediumSlateBlue = Color.MediumSlateBlue;
        public static Color MediumSpringGreen = Color.MediumSpringGreen;
        public static Color MediumTurquoise = Color.MediumTurquoise;
        public static Color MediumVioletRed = Color.MediumVioletRed;
        public static Color MidnightBlue = Color.MidnightBlue;
        public static Color MintCream = Color.MintCream;
        public static Color MistyRose = Color.MistyRose;
        public static Color Moccasin = Color.Moccasin;
        public static Color NavajoWhite = Color.NavajoWhite;
        public static Color Navy = Color.Navy;
        public static Color OldLace = Color.OldLace;
        public static Color Olive = Color.Olive;
        public static Color OliveDrab = Color.OliveDrab;
        public static Color Orange = Color.Orange;
        public static Color OrangeRed = Color.OrangeRed;
        public static Color Orchid = Color.Orchid;
        public static Color PaleGoldenrod = Color.PaleGoldenrod;
        public static Color PaleGreen = Color.PaleGreen;
        public static Color PaleTurquoise = Color.PaleTurquoise;
        public static Color PaleVioletRed = Color.PaleVioletRed;
        public static Color PapayaWhip = Color.PapayaWhip;
        public static Color PeachPuff = Color.PeachPuff;
        public static Color Peru = Color.Peru;
        public static Color Pink = Color.Pink;
        public static Color Plum = Color.Plum;
        public static Color PowderBlue = Color.PowderBlue;
        public static Color Purple = Color.Purple;
        public static Color Red = Color.Red;
        public static Color RosyBrown = Color.RosyBrown;
        public static Color RoyalBlue = Color.RoyalBlue;
        public static Color SaddleBrown = Color.SaddleBrown;
        public static Color Salmon = Color.Salmon;
        public static Color SandyBrown = Color.SandyBrown;
        public static Color SeaGreen = Color.SeaGreen;
        public static Color SeaShell = Color.SeaShell;
        public static Color Sienna = Color.Sienna;
        public static Color Silver = Color.Silver;
        public static Color SkyBlue = Color.SkyBlue;
        public static Color SlateBlue = Color.SlateBlue;
        public static Color SlateGray = Color.SlateGray;
        public static Color Snow = Color.Snow;
        public static Color SpringGreen = Color.SpringGreen;
        public static Color SteelBlue = Color.SteelBlue;
        public static Color Tan = Color.Tan;
        public static Color Teal = Color.Teal;
        public static Color Thistle = Color.Thistle;
        public static Color Tomato = Color.Tomato;
        public static Color Turquoise = Color.Turquoise;
        public static Color Violet = Color.Violet;
        public static Color Wheat = Color.Wheat;
        public static Color White = Color.White;
        public static Color WhiteSmoke = Color.WhiteSmoke;
        public static Color Yellow = Color.Yellow;
        public static Color YellowGreen = Color.YellowGreen;



        public static Color getColorTransparent(Color color, float alpha)
        {
            Color toReturn = new Color(color.R,color.G,color.B,alpha);
            return toReturn;
        }
    }
}
